Repository Say-Better/Android-Educator-APP, pull requests merged in 2024-08, with the labels that each got.

#11 [Feat/#10/userinfo] 사용자 정보 입력 UI 구성
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/saybettereducator/ui/login/LoginActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/theme/Color.kt
  app/src/main/java/com/example/saybettereducator/ui/theme/Type.kt
  app/src/main/java/com/example/saybettereducator/ui/userinfo/UserInfoActivity.kt
  app/src/main/res/drawable/cancel_button.xml
  app/src/main/res/drawable/cancel_button_2.xml
  app/src/main/res/drawable/login_illust_educator.png
  app/src/main/res/drawable/profile_button.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/xml/file_paths.xml
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: :hammer_and_pick: chore, :sparkles: feat

#12 [Feat/#6/webrtc] 화상통화 기능 추가
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/saybettereducator/model/remote/dto/DataModel.kt
  app/src/main/java/com/example/saybettereducator/model/remote/dto/UserStatus.kt
  app/src/main/java/com/example/saybettereducator/ui/MainActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/login/LoginActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/videoCall/VideoCallActivity.kt
  app/src/main/java/com/example/saybettereducator/utils/FirebaseFieldNames.kt
  app/src/main/java/com/example/saybettereducator/utils/MyApplication.kt
  app/src/main/java/com/example/saybettereducator/utils/MyEventListener.kt
  app/src/main/java/com/example/saybettereducator/utils/module/AppModule.kt
  app/src/main/java/com/example/saybettereducator/utils/permission/PermissionCheck.kt
  app/src/main/java/com/example/saybettereducator/utils/webrtc/firebaseClient/FirebaseClient.kt
  app/src/main/java/com/example/saybettereducator/utils/webrtc/repository/MainRepository.kt
  app/src/main/java/com/example/saybettereducator/utils/webrtc/service/MainService.kt
  app/src/main/java/com/example/saybettereducator/utils/webrtc/service/MainServiceActions.kt
  app/src/main/java/com/example/saybettereducator/utils/webrtc/service/MainServiceRepository.kt
  app/src/main/java/com/example/saybettereducator/utils/webrtc/webrtcClient/MyPeerObserver.kt
  app/src/main/java/com/example/saybettereducator/utils/webrtc/webrtcClient/MySdpObserver.kt
  app/src/main/java/com/example/saybettereducator/utils/webrtc/webrtcClient/WebRTCClient.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: :sparkles: feat

#14 [Feat/#6/webrtc 2] 화상통화 기능 추가 마무리
  app/src/main/java/com/example/saybettereducator/ui/videoCall/VideoCallActivity.kt
  app/src/main/java/com/example/saybettereducator/utils/webrtc/repository/MainRepository.kt
  app/src/main/java/com/example/saybettereducator/utils/webrtc/service/MainService.kt
  app/src/main/java/com/example/saybettereducator/utils/webrtc/service/MainServiceActions.kt
  app/src/main/java/com/example/saybettereducator/utils/webrtc/service/MainServiceRepository.kt
Labels: :rainbow: frontend, :sparkles: feat

#15 [Feat/#13/refactor] mvi 패턴 구조 적용
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/saybettereducator/App.kt
  app/src/main/java/com/example/saybettereducator/MainActivity.kt
  app/src/main/java/com/example/saybettereducator/domain/model/DataModel.kt
  app/src/main/java/com/example/saybettereducator/domain/model/UserStatus.kt
  app/src/main/java/com/example/saybettereducator/ui/activity/LoginActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/activity/MainActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/activity/SplashActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/activity/VideoCallActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/common/ErrorSnackBar.kt
  app/src/main/java/com/example/saybettereducator/ui/common/IntentHandler.kt
  app/src/main/java/com/example/saybettereducator/ui/common/MviViewModel.kt
  app/src/main/java/com/example/saybettereducator/ui/intent/UserInfoIntent.kt
  app/src/main/java/com/example/saybettereducator/ui/model/UserInfoState.kt
  app/src/main/java/com/example/saybettereducator/ui/navigation/AppNavHost.kt
  app/src/main/java/com/example/saybettereducator/ui/sideeffect/UserInfoSideEffect.kt
  app/src/main/java/com/example/saybettereducator/ui/userinfo/UserInfoActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/view/components/UserInfoBottomBar.kt
  app/src/main/java/com/example/saybettereducator/ui/view/components/UserInfoNameInputBox.kt
  app/src/main/java/com/example/saybettereducator/ui/view/components/UserInfoProfilePopup.kt
  app/src/main/java/com/example/saybettereducator/ui/view/components/UserInfoTitleText.kt
  app/src/main/java/com/example/saybettereducator/ui/view/components/UserInfoTopAppBar.kt
  app/src/main/java/com/example/saybettereducator/ui/view/screen/CalendarScreen.kt
  app/src/main/java/com/example/saybettereducator/ui/view/screen/HomeScreen.kt
  app/src/main/java/com/example/saybettereducator/ui/view/screen/LearnerScreen.kt
  app/src/main/java/com/example/saybettereducator/ui/view/screen/LoginSuccessScreen.kt
  app/src/main/java/com/example/saybettereducator/ui/view/screen/SolutionScreen.kt
  app/src/main/java/com/example/saybettereducator/ui/view/screen/UserInfoScreen.kt
  app/src/main/java/com/example/saybettereducator/ui/viewmodel/UserInfoViewModel.kt
  app/src/main/java/com/example/saybettereducator/utils/image/CameraUtil.kt
  app/src/main/java/com/example/saybettereducator/utils/image/GalleryUtil.kt
  app/src/main/java/com/example/saybettereducator/utils/webrtc/firebaseClient/FirebaseClient.kt
  app/src/main/java/com/example/saybettereducator/utils/webrtc/repository/MainRepository.kt
  app/src/main/java/com/example/saybettereducator/utils/webrtc/service/MainService.kt
  app/src/main/java/com/example/saybettereducator/utils/webrtc/webrtcClient/WebRTCClient.kt
Labels: :hammer_and_pick: chore, :recycle: refactor

#18 [Refactor/#16/build] 빌드 정상화
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/saybettereducator/MainActivity.kt
  app/src/main/java/com/example/saybettereducator/config/SayBetterApplication.kt
  app/src/main/java/com/example/saybettereducator/ui/activity/LoginActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/activity/MaActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/activity/MainActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/components/main/MainBottomNavigationBar.kt
  app/src/main/java/com/example/saybettereducator/ui/components/main/MainTopBar.kt
  app/src/main/java/com/example/saybettereducator/ui/components/userinfo/UserInfoBottomBar.kt
  app/src/main/java/com/example/saybettereducator/ui/components/userinfo/UserInfoNameInputBox.kt
  app/src/main/java/com/example/saybettereducator/ui/components/userinfo/UserInfoProfilePopup.kt
  app/src/main/java/com/example/saybettereducator/ui/components/userinfo/UserInfoTitleText.kt
  app/src/main/java/com/example/saybettereducator/ui/components/userinfo/UserInfoTopAppBar.kt
  app/src/main/java/com/example/saybettereducator/ui/navigation/AppNavHost.kt
  app/src/main/java/com/example/saybettereducator/ui/view/CalendarScreen.kt
  app/src/main/java/com/example/saybettereducator/ui/view/HomeScreen.kt
  app/src/main/java/com/example/saybettereducator/ui/view/LearnerScreen.kt
  app/src/main/java/com/example/saybettereducator/ui/view/LoginSuccessScreen.kt
  app/src/main/java/com/example/saybettereducator/ui/view/SolutionScreen.kt
  app/src/main/java/com/example/saybettereducator/ui/view/UserInfoScreen.kt
  app/src/main/java/com/example/saybettereducator/utils/MyApplication.kt
Labels: :bug: bug, :recycle: refactor

#20 [Refactor/#17/webrtc migration] MVI 패턴으로의 마이그레이션 및 캠 화면 디자인에 맞게 수정
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/saybettereducator/data/api/helper/FirebaseClient.kt
  app/src/main/java/com/example/saybettereducator/data/api/helper/WebRTCClient.kt
  app/src/main/java/com/example/saybettereducator/data/model/DataModel.kt
  app/src/main/java/com/example/saybettereducator/data/model/FirebaseFieldNames.kt
  app/src/main/java/com/example/saybettereducator/data/model/MainServiceActions.kt
  app/src/main/java/com/example/saybettereducator/data/model/UserStatus.kt
  app/src/main/java/com/example/saybettereducator/data/repository/MainRepository.kt
  app/src/main/java/com/example/saybettereducator/data/repository/MainServiceRepository.kt
  app/src/main/java/com/example/saybettereducator/data/service/MainService.kt
  app/src/main/java/com/example/saybettereducator/di/SayBetterAppModule.kt
  app/src/main/java/com/example/saybettereducator/di/SayBetterApplication.kt
  app/src/main/java/com/example/saybettereducator/ui/activity/LoginActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/activity/MaActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/activity/MainActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/activity/VideoCallActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/intent/VideoCallIntent.kt
  app/src/main/java/com/example/saybettereducator/ui/model/VideoCallState.kt
  app/src/main/java/com/example/saybettereducator/ui/navigation/AppNavHost.kt
  app/src/main/java/com/example/saybettereducator/ui/sideeffect/VideoCallSideEffect.kt
  app/src/main/java/com/example/saybettereducator/ui/viewmodel/VideoCallViewModel.kt
  app/src/main/java/com/example/saybettereducator/utils/webrtcObserver/MyPeerObserver.kt
  app/src/main/java/com/example/saybettereducator/utils/webrtcObserver/MySdpObserver.kt
Labels: :recycle: refactor, 🎨 style

#22 [Feature/#19/solution] 솔루션 진행 ui 구현
  app/src/main/java/com/example/saybettereducator/data/model/Symbol.kt
  app/src/main/java/com/example/saybettereducator/di/AppModule.kt
  app/src/main/java/com/example/saybettereducator/ui/components/progress/ProgressBasicBtn.kt
  app/src/main/java/com/example/saybettereducator/ui/components/progress/ProgressBottomBar.kt
  app/src/main/java/com/example/saybettereducator/ui/components/progress/ProgressBottomSheet.kt
  app/src/main/java/com/example/saybettereducator/ui/components/progress/ProgressBottomSheetChanceView.kt
  app/src/main/java/com/example/saybettereducator/ui/components/progress/ProgressBottomSheetSymbol.kt
  app/src/main/java/com/example/saybettereducator/ui/components/progress/ProgressBottomSheetTitle.kt
  app/src/main/java/com/example/saybettereducator/ui/components/progress/ProgressLearningView.kt
  app/src/main/java/com/example/saybettereducator/ui/components/progress/ProgressModeView.kt
  app/src/main/java/com/example/saybettereducator/ui/components/progress/ProgressTopBar.kt
  app/src/main/java/com/example/saybettereducator/ui/components/progress/SymbolCard.kt
  app/src/main/java/com/example/saybettereducator/ui/components/userinfo/UserInfoNameInputBox.kt
  app/src/main/java/com/example/saybettereducator/ui/components/userinfo/UserInfoProfilePopup.kt
  app/src/main/java/com/example/saybettereducator/ui/intent/ProgressIntent.kt
  app/src/main/java/com/example/saybettereducator/ui/model/ProgressState.kt
  app/src/main/java/com/example/saybettereducator/ui/navigation/AppNavHost.kt
  app/src/main/java/com/example/saybettereducator/ui/navigation/VideoCallNavHost.kt
  app/src/main/java/com/example/saybettereducator/ui/sideeffect/ProgressSideEffect.kt
  app/src/main/java/com/example/saybettereducator/ui/theme/Color.kt
  app/src/main/java/com/example/saybettereducator/ui/view/ProgressScreen.kt
  app/src/main/java/com/example/saybettereducator/ui/viewmodel/ProgressViewModel.kt
  app/src/main/res/drawable/progress_add_symbol.xml
  app/src/main/res/drawable/progress_chance_btn.xml
  app/src/main/res/drawable/progress_mode_1.xml
  app/src/main/res/drawable/progress_mode_1_active.xml
  app/src/main/res/drawable/progress_mode_2.xml
  app/src/main/res/drawable/progress_mode_2_active.xml
  app/src/main/res/drawable/progress_mode_3.xml
  app/src/main/res/drawable/progress_mode_3_active.xml
  app/src/main/res/drawable/progress_mode_4.xml
  app/src/main/res/drawable/progress_mode_4_active.xml
  app/src/main/res/drawable/progress_timer.xml
  app/src/main/res/drawable/progress_volume.xml
  app/src/main/res/drawable/solution_end_btn.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles: feat

#24 [feat/#21/webtrc-dataChannel] WebRTC DataChannel 추가
  app/src/main/java/com/example/saybettereducator/data/api/helper/WebRTCClient.kt
  app/src/main/java/com/example/saybettereducator/data/repository/MainRepository.kt
  app/src/main/java/com/example/saybettereducator/ui/activity/VideoCallActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/intent/VideoCallIntent.kt
  app/src/main/java/com/example/saybettereducator/ui/viewmodel/VideoCallViewModel.kt
Labels: :sparkles: feat

#26 [Feature/#23/screen merge] 솔루션 준비화면, 진행화면 병합
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/saybettereducator/data/repository/MainRepository.kt
  app/src/main/java/com/example/saybettereducator/ui/activity/MaActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/activity/MainActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/activity/SessionActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/activity/VideoCallActivity.kt
  app/src/main/java/com/example/saybettereducator/ui/components/session/ProgressBasicBtn.kt
  app/src/main/java/com/example/saybettereducator/ui/components/session/ProgressBottomBar.kt
  app/src/main/java/com/example/saybettereducator/ui/components/session/ProgressBottomSheet.kt
  app/src/main/java/com/example/saybettereducator/ui/components/session/ProgressBottomSheetChanceView.kt
  app/src/main/java/com/example/saybettereducator/ui/components/session/ProgressBottomSheetSymbol.kt
  app/src/main/java/com/example/saybettereducator/ui/components/session/ProgressBottomSheetTitle.kt
  app/src/main/java/com/example/saybettereducator/ui/components/session/ProgressLearningView.kt
  app/src/main/java/com/example/saybettereducator/ui/components/session/ProgressModeView.kt
  app/src/main/java/com/example/saybettereducator/ui/components/session/ProgressTopBar.kt
  app/src/main/java/com/example/saybettereducator/ui/components/session/ReadyHelloBtn.kt
  app/src/main/java/com/example/saybettereducator/ui/components/session/ReadyTopBar.kt
  app/src/main/java/com/example/saybettereducator/ui/components/session/SessionBottomBar.kt
  app/src/main/java/com/example/saybettereducator/ui/components/session/SessionVideoView.kt
  app/src/main/java/com/example/saybettereducator/ui/components/session/SymbolCard.kt
  app/src/main/java/com/example/saybettereducator/ui/intent/SessionIntent.kt
  app/src/main/java/com/example/saybettereducator/ui/intent/VideoCallIntent.kt
  app/src/main/java/com/example/saybettereducator/ui/model/SessionState.kt
  app/src/main/java/com/example/saybettereducator/ui/navigation/AppNavHost.kt
  app/src/main/java/com/example/saybettereducator/ui/navigation/VideoCallNavHost.kt
  app/src/main/java/com/example/saybettereducator/ui/sideeffect/SessionSideEffect.kt
  app/src/main/java/com/example/saybettereducator/ui/sideeffect/VideoCallSideEffect.kt
  app/src/main/java/com/example/saybettereducator/ui/view/ProgressScreen.kt
  app/src/main/java/com/example/saybettereducator/ui/viewmodel/SessionViewModel.kt
  app/src/main/java/com/example/saybettereducator/ui/viewmodel/VideoCallViewModel.kt
Labels: :recycle: refactor, :sparkles: feat

#28 ♻️ Refactor: 임시 MaActivity 삭제
  app/src/main/java/com/example/saybettereducator/ui/activity/MaActivity.kt
Labels: :recycle: refactor
